package report

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// Section represents a report section from a tool result.
type Section struct {
	Title   string `json:"title"`
	Tool    string `json:"tool"`
	Content string `json:"content"`
}

// Request is the input for report generation.
type Request struct {
	Title    string    `json:"title"`
	Sections []Section `json:"sections"`
	Format   string    `json:"format"` // "markdown" or "html"
}

// Generator produces reports in different formats.
type Generator struct{}

// NewGenerator creates a report generator.
func NewGenerator() *Generator {
	return &Generator{}
}

// Generate produces a report in the requested format.
func (g *Generator) Generate(req *Request) (string, error) {
	if req.Title == "" {
		req.Title = "Security Assessment Report"
	}
	if req.Format == "" {
		req.Format = "markdown"
	}

	switch req.Format {
	case "markdown":
		return g.generateMarkdown(req), nil
	case "html":
		return g.generateHTML(req), nil
	default:
		return "", fmt.Errorf("unsupported format: %s (use 'markdown' or 'html')", req.Format)
	}
}

// GenerateFromJSON creates a report from a JSON request body.
func (g *Generator) GenerateFromJSON(data json.RawMessage) (string, error) {
	var req Request
	if err := json.Unmarshal(data, &req); err != nil {
		return "", fmt.Errorf("invalid report request: %w", err)
	}
	return g.Generate(&req)
}

func (g *Generator) generateMarkdown(req *Request) string {
	var sb strings.Builder

	sb.WriteString("# ")
	sb.WriteString(req.Title)
	sb.WriteString("\n\n")

	fmt.Fprintf(&sb, "**Generated**: %s\n\n", time.Now().UTC().Format("2006-01-02 15:04:05 UTC"))
	sb.WriteString("---\n\n")

	sb.WriteString("## Table of Contents\n\n")
	for i, sec := range req.Sections {
		fmt.Fprintf(&sb, "%d. [%s](#section-%d)\n", i+1, sec.Title, i+1)
	}
	sb.WriteString("\n---\n\n")

	for i, sec := range req.Sections {
		fmt.Fprintf(&sb, "## %d. %s {#section-%d}\n\n", i+1, sec.Title, i+1)
		if sec.Tool != "" {
			fmt.Fprintf(&sb, "*Tool: %s*\n\n", sec.Tool)
		}
		sb.WriteString(sec.Content)
		sb.WriteString("\n\n")
	}

	sb.WriteString("---\n\n*Report generated by RedHands MCP Server*\n")
	return sb.String()
}

func (g *Generator) generateHTML(req *Request) string {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>`)
	sb.WriteString(htmlEscape(req.Title))
	sb.WriteString(`</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #1a1a1a; line-height: 1.6; }
h1 { color: #c0392b; border-bottom: 3px solid #c0392b; padding-bottom: 0.5rem; }
h2 { color: #2c3e50; border-bottom: 1px solid #ecf0f1; padding-bottom: 0.3rem; margin-top: 2rem; }
.meta { color: #7f8c8d; font-size: 0.9rem; }
.tool-tag { background: #ecf0f1; padding: 0.2rem 0.5rem; border-radius: 3px; font-size: 0.85rem; color: #2c3e50; }
.content { background: #f8f9fa; border-left: 4px solid #3498db; padding: 1rem; margin: 1rem 0; white-space: pre-wrap; font-family: 'Courier New', monospace; font-size: 0.9rem; overflow-x: auto; }
.toc { background: #f8f9fa; padding: 1rem 1.5rem; border-radius: 5px; margin: 1rem 0; }
.toc a { color: #2980b9; text-decoration: none; }
.toc a:hover { text-decoration: underline; }
footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #ecf0f1; color: #95a5a6; font-size: 0.85rem; }
</style>
</head>
<body>
`)

	fmt.Fprintf(&sb, "<h1>%s</h1>\n", htmlEscape(req.Title))
	fmt.Fprintf(&sb, "<p class=\"meta\">Generated: %s</p>\n\n", time.Now().UTC().Format("2006-01-02 15:04:05 UTC"))

	sb.WriteString("<div class=\"toc\">\n<h3>Table of Contents</h3>\n<ol>\n")
	for i, sec := range req.Sections {
		fmt.Fprintf(&sb, "<li><a href=\"#section-%d\">%s</a></li>\n", i+1, htmlEscape(sec.Title))
	}
	sb.WriteString("</ol>\n</div>\n\n")

	for i, sec := range req.Sections {
		fmt.Fprintf(&sb, "<h2 id=\"section-%d\">%d. %s</h2>\n", i+1, i+1, htmlEscape(sec.Title))
		if sec.Tool != "" {
			fmt.Fprintf(&sb, "<span class=\"tool-tag\">%s</span>\n", htmlEscape(sec.Tool))
		}
		fmt.Fprintf(&sb, "<div class=\"content\">%s</div>\n\n", htmlEscape(sec.Content))
	}

	sb.WriteString("<footer>Report generated by RedHands MCP Server</footer>\n")
	sb.WriteString("</body>\n</html>")

	return sb.String()
}

func htmlEscape(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "\"", "&quot;")
	return s
}
